### ISSUE TITLE
Multiple tests in the grid client tests are failing

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#1046]
### Description

Multiple tests in the grid client tests are failing with the following error.

```
 var logFunction = require('debug')(identifier);
                                      ^

TypeError: require(...) is not a function
    at Object.createBufferingLogger [as BufferingLogger] (/home/mohamed/Desktop/Threefold Repos/sdkts/tfgrid-sdk-ts/node_modules/websocket/lib/utils.js:24:39)
    at new WebSocketConnection (/home/mohamed/Desktop/Threefold Repos/sdkts/tfgrid-sdk-ts/node_modules/websocket/lib/WebSocketConnection.js:42:25)
    at WebSocketClient.Object.<anonymous>.WebSocketClient.succeedHandshake (/home/mohamed/Desktop/Threefold Repos/sdkts/tfgrid-sdk-ts/node_modules/websocket/lib/WebSocketClient.js:343:22)
    at WebSocketClient.Object.<anonymous>.WebSocketClient.validateHandshake (/home/mohamed/Desktop/Threefold Repos/sdkts/tfgrid-sdk-ts/node_modules/websocket/lib/WebSocketClient.js:332:10)
    at ClientRequest.handleRequestUpgrade (/home/mohamed/Desktop/Threefold Repos/sdkts/tfgrid-sdk-ts/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketOnData (node:_http_client:582:11)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v18.14.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Logs 

Full test results from the latest workflow run. https://github.com/threefoldtech/tfgrid-sdk-ts/runs/16162097060

### Steps to reproduce

- Run grid client [tests](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/docs/tests.md).

**Comment by mohamedamer453** [comment]
After running the tests locally they appear to be passing but the suite itself fails with the same error mentioned above.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a0ca7ed3-8765-47b4-9618-0b0cc73d68e5)

**Comment by AhmedHanafy725** [comment]
found the original error on the workflow and it was 

```
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'isConnected')

      58 |             if (connection && this.api.isConnected)
      59 |                 return;
    > 60 |             if (!connection && !this.api.isConnected)
         |                                          ^
      61 |                 return;
      62 |             await new Promise(f => setTimeout(f, 100));
      63 |         }

      at TFClient.isConnected [as wait] (../tfchain_client/dist/node/client.js:60:42)
      at TFClient.disconnect (../tfchain_client/dist/node/client.js:114:13)
      at GridClient.disconnect (src/client.ts:219:24)
      at Object.<anonymous> (tests/modules/kvstore.test.ts:63:10)
```

the issue is the client on disconnect doesn't drop the event listener, so the client delete the api object and try to create another one while disconnecting.

### The Solution
the client should properly drop the event when the disconnect method is called

**Comment by A-Harby** [comment]
Verified, It pass now.
From the workflow
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/6006557514
And locally
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/98823cc2-3eb0-4607-9623-9eb01e6b3f9f)
