### ISSUE TITLE
`yarn lerna run build` keep failing

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2162]
### Description

A clear description of the bug is:

After cloning the repo and installing it, every time I run Learn Build, it fails in the `@threefold/dashboard`

Must include any relevant identifiers, like:

- **Network**: dev

- **Version**: lastest, development branch

### Steps to reproduce

- Clone repo.
- git pull
- yarn install
- yarn lerna run build

### Logs/Alerts

Must include if available:

- Logs/Alerts.
```
yarn lerna run build
yarn run v1.22.19
$ /home/harby/Projects/tfgrid-sdk-ts/node_modules/.bin/lerna run build
lerna notice cli v6.6.1
lerna WARN EWORKSPACES Workspaces exist in the root package.json, but Lerna is not configured to use them.
lerna WARN EWORKSPACES To fix this and have Lerna use workspaces to resolve packages, set `useWorkspaces: true` in lerna.json.
lerna WARN EPACKAGES No packages defined in lerna.json. Defaulting to packages in packages/*

    ✔  @threefold/rmb_peer_client:build (1s)
    ✔  @threefold/rmb_peer_server:build (1s)
    ✔  @threefold/types:build (1s)
    ✔  @threefold/tfchain_client:build (4s)
    ✔  @threefold/gridproxy_client:build (6s)
    ✔  @threefold/graphql_client:build (7s)
    ✔  @threefold/rmb_direct_client:build (4s)
    ✔  @threefold/stats:build (12s)
    ✔  @threefold/grid_client:build (4s)
    ✔  @threefold/monitoring:build (6s)
    ✔  @threefold/grid_http_server:build (3s)
    ✔  @threefold/grid_rmb_server:build (3s)

    ✖  @threefold/dashboard:build
       > @threefold/dashboard@2.3.0-alpha9 build
       > vue-cli-service build
       
       Browserslist: caniuse-lite is outdated. Please run:
         npx update-browserslist-db@latest
         Why you should do it regularly: https://github.com/browserslist/update-db#readme
        ERROR  Error: 
               
               Vue packages version mismatch:
               
               - vue@3.3.2 (/home/harby/Projects/tfgrid-sdk-ts/node_modules/vue/index.js)
               - vue-template-compiler@2.7.14 (/home/harby/Projects/tfgrid-sdk-ts/node_modules/vue-template-compiler/package.json)
               
               This may cause things to work incorrectly. Make sure to use the same version for both.
               If you are using vue-loader@>=10.0, simply update vue-template-compiler.
               If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
               
       Error: 
       
       Vue packages version mismatch:
       
       - vue@3.3.2 (/home/harby/Projects/tfgrid-sdk-ts/node_modules/vue/index.js)
       - vue-template-compiler@2.7.14 (/home/harby/Projects/tfgrid-sdk-ts/node_modules/vue-template-compiler/package.json)
       
       This may cause things to work incorrectly. Make sure to use the same version for both.
       If you are using vue-loader@>=10.0, simply update vue-template-compiler.
       If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
       
           at Object.<anonymous> (/home/harby/Projects/tfgrid-sdk-ts/node_modules/vue-template-compiler/index.js:10:9)
           at Module._compile (node:internal/modules/cjs/loader:1256:14)
           at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
           at Module.load (node:internal/modules/cjs/loader:1119:32)
           at Module._load (node:internal/modules/cjs/loader:960:12)
           at Module.require (node:internal/modules/cjs/loader:1143:19)
           at require (node:internal/modules/cjs/helpers:110:18)
           at Object.<anonymous> (/home/harby/Projects/tfgrid-sdk-ts/node_modules/vuetify-loader/lib/loader.js:3:18)
           at Module._compile (node:internal/modules/cjs/loader:1256:14)
           at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
       npm ERR! Lifecycle script `build` failed with error: 
       npm ERR! Error: command failed 
       npm ERR!   in workspace: @threefold/dashboard@2.3.0-alpha9 
       npm ERR!   at location: /home/harby/Projects/tfgrid-sdk-ts/packages/dashboard 
       
    ✔  @threefold/newstats:build (13s)
    ✔  @threefold/ui:build (35s)
    ✔  @threefold/playground:build (1m)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Ran target build for 16 projects (1m)
 
    ✔    15/16 succeeded [0 read from cache]
 
    ✖    1/16 targets failed, including the following:
         - @threefold/dashboard:build
 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
- Screenshots or screen records.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/50dc7706-e54f-479a-948f-08fea9cb861c)

**Comment by ramezsaeed** [comment]
obsolete package, will not be used anymore
