### ISSUE TITLE
🐞 [Bug]: WebSocket was closed before the connection was established

### ISSUE THREAD

**Issue by costarassco** [threefoldtech/tfgrid-sdk-ts#2611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

This issue was observed before and looks like this is the same as these two:

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1054
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/992

I create a long term connection using a grid client and it was working awesome after the updates made in the latest versions, but now it's still can be observed

### Steps To Reproduce

1) Create a long term connection using a grid client
2) Observe the abort handshake error

### which network/s did you face the problem on?

Main

### version

2.3.5

### Relevant screenshots/screen records

Waiting for the rmb responses to be received before closing the connection
Waiting for the rmb responses to be received before closing the connection
Waiting for the rmb responses to be received before closing the connection
Waiting for the rmb responses to be received before closing the connection
disconnecting
2024-04-22 18:30:17        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-04-22 18:30:17        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
Waiting for the rmb responses to be received before closing the connection
disconnecting
2024-04-22 18:31:17        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-04-22 18:31:17        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
Waiting for the rmb responses to be received before closing the connection
disconnecting
2024-04-22 18:31:43        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-04-22 18:31:43        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
Waiting for the rmb responses to be received before closing the connection
disconnecting
2024-04-22 18:31:46        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-04-22 18:31:46        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
disconnecting
2024-04-22 18:47:51        RPC-CORE: subscribeRuntimeVersion(): RuntimeVersion:: cannot call send() while not connected

/app/threefold/node_modules/ws/lib/websocket.js:292
      abortHandshake(this, this._req, msg);
      ^
Error: WebSocket was closed before the connection was established
    at WebSocket.close (/app/threefold/node_modules/ws/lib/websocket.js:292:7)
    at Client.disconnect (/app/threefold/node_modules/@threefold/rmb_direct_client/dist/node/client.js:183:22)

### Relevant log output

```console
Waiting for the rmb responses to be received before closing the connection
Waiting for the rmb responses to be received before closing the connection
Waiting for the rmb responses to be received before closing the connection
Waiting for the rmb responses to be received before closing the connection
disconnecting
2024-04-22 18:30:17        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-04-22 18:30:17        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
Waiting for the rmb responses to be received before closing the connection
disconnecting
2024-04-22 18:31:17        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-04-22 18:31:17        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
Waiting for the rmb responses to be received before closing the connection
disconnecting
2024-04-22 18:31:43        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-04-22 18:31:43        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
Waiting for the rmb responses to be received before closing the connection
disconnecting
2024-04-22 18:31:46        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-04-22 18:31:46        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
disconnecting
2024-04-22 18:47:51        RPC-CORE: subscribeRuntimeVersion(): RuntimeVersion:: cannot call send() while not connected

/app/threefold/node_modules/ws/lib/websocket.js:292
      abortHandshake(this, this._req, msg);
      ^
Error: WebSocket was closed before the connection was established
    at WebSocket.close (/app/threefold/node_modules/ws/lib/websocket.js:292:7)
    at Client.disconnect (/app/threefold/node_modules/@threefold/rmb_direct_client/dist/node/client.js:183:22)
```

**Comment by berelton** [comment]
Hello @AhmedHanafy725 , here is the code:

```
import { GridClient, NetworkEnv } from "@threefold/grid_client";

const options = {
  network: NetworkEnv.main,
  mnemonic,
  storeSecret: "coolSecretPhrase",
};

const gridClient = new GridClient(options);
await gridClient.connect();
```

ref: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/992

**Comment by khaledyoussef24** [comment]
how can we verify this ?
