### ISSUE TITLE
🐞 [Bug]:  Incorrect count of successful and failed deployments when executing mass deployment script

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#2729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

While executing the [mass deployment script](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/scripts/mass_deployments.ts). Despite all deployments failing, It reported 5 successful deployments and 0 failed deployments.

### which network/s did you face the problem on?

QA

### version

2.4.0

### Relevant screenshots/screen records

![2024-05-19_19-32](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/76ad8cc9-2f99-4d7f-96ca-1f4c62d41365)

### Relevant log output

```console
Error: RMBError: Failed to send request to twinId 515 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 3 is offline
Error: RMBError: Failed to send request to twinId 10 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 2 is offline
Error: RMBError: Failed to send request to twinId 9 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 28 is offline
Error: RMBError: Failed to send request to twinId 514 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Preparing Batch 1: 0.061ms
Merging workloads
'Successfully handled and saved contracts for some twin deployments'
Batch 1: 1.917s
Ping Nodes: 1.271s
Node 3 is offline
Error: RMBError: Failed to send request to twinId 10 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 2 is offline
Error: RMBError: Failed to send request to twinId 9 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 29 is offline
Error: RMBError: Failed to send request to twinId 515 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 28 is offline
Error: RMBError: Failed to send request to twinId 514 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Preparing Batch 2: 0.067ms
Merging workloads
'Successfully handled and saved contracts for some twin deployments'
Batch 2: 1.595s
Ping Nodes: 1.317s
Node 2 is offline
Error: RMBError: Failed to send request to twinId 9 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 29 is offline
Error: RMBError: Failed to send request to twinId 515 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 3 is offline
Error: RMBError: Failed to send request to twinId 10 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 28 is offline
Error: RMBError: Failed to send request to twinId 514 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Preparing Batch 3: 0.046ms
Merging workloads
'Successfully handled and saved contracts for some twin deployments'
Batch 3: 1.634s
Ping Nodes: 1.268s
Node 2 is offline
Error: RMBError: Failed to send request to twinId 9 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 29 is offline
Error: RMBError: Failed to send request to twinId 515 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 3 is offline
Error: RMBError: Failed to send request to twinId 10 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 28 is offline
Error: RMBError: Failed to send request to twinId 514 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Preparing Batch 4: 0.069ms
Merging workloads
'Successfully handled and saved contracts for some twin deployments'
Batch 4: 1.582s
Ping Nodes: 1.394s
Node 2 is offline
Error: RMBError: Failed to send request to twinId 9 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 29 is offline
Error: RMBError: Failed to send request to twinId 515 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 3 is offline
Error: RMBError: Failed to send request to twinId 10 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Node 28 is offline
Error: RMBError: Failed to send request to twinId 514 with command: zos.system.version, payload: 
         RMBError: 104 invalid envelope signature: sr25519 signature verification failed
    at /home/mayar/tfgrid-sdk-ts/packages/rmb_direct_client/dist/node/client.js:350:32 {
  code: 5,
  module: 'Generic'
}
Preparing Batch 5: 0.018ms
Merging workloads
'Successfully handled and saved contracts for some twin deployments'
Batch 5: 1.731s
Total Deployment Time: 8.460s
'Successful Deployments: 5'
'Failed Deployments: 0'
'Failed deployments errors: '
'No online nodes available for deployment'
'---------------------------------------------'
'No online nodes available for deployment'
'---------------------------------------------'
'No online nodes available for deployment'
'---------------------------------------------'
'No online nodes available for deployment'
'---------------------------------------------'
'No online nodes available for deployment'
'---------------------------------------------'
'Failed Nodes: '
29
'---------------------------------------------'
3
'---------------------------------------------'
2
'---------------------------------------------'
28
'---------------------------------------------'
3
'---------------------------------------------'
2
'---------------------------------------------'
29
'---------------------------------------------'
28
'---------------------------------------------'
2
'---------------------------------------------'
29
'---------------------------------------------'
3
'---------------------------------------------'
28
'---------------------------------------------'
2
'---------------------------------------------'
29
'---------------------------------------------'
3
'---------------------------------------------'
28
'---------------------------------------------'
2
'---------------------------------------------'
29
'---------------------------------------------'
3
'---------------------------------------------'
28
'---------------------------------------------' ```
```

**Comment by AlaaElattar** [comment]
- I tested it with many deployment of different batches and it worked fine.
- can't reproduce it.

![Screenshot from 2024-05-22 11-42-45](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/9a6f6a06-1cab-4528-a527-4bdcdaff164e)

![Screenshot from 2024-05-22 10-24-36](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/d55f9165-8907-4b64-83c3-b3a7298af8a5)

**Comment by A-Harby** [comment]
I have tried a few times; it has never been all successful, but the counts look normal.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7eb49df7-0c67-4c05-9de7-cef8784e677b)
