### ISSUE TITLE
(Mainnet)🐞 [Bug]: Error when GPU is toggled on 

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#2916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I get the following console error when I toggle GPU on in FullVM depoy 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/034f2c4c-9d2d-421e-a617-5a1c51237102)

### Steps To Reproduce

1. go to deploy/virtual machines/ fullVM
2. toggle GPu filter on 
3. open console and view error

### which network/s did you face the problem on?

Dev

### version

2.5

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/cee6b7f9-4d9d-4b66-ba09-abc167d484b5)

### Relevant log output

```console
[Uncaught Error]
- Message: Cannot access 'fakeService' before initialization
- Stack: ReferenceError: Cannot access 'fakeService' before initialization
    at bindStatus (http://localhost:5173/src/components/node_selector/TfSelectGpu.vue:60:7)
    at useWatchDeep.immediate (http://localhost:5173/src/components/node_selector/TfSelectGpu.vue:30:9)
    at http://localhost:5173/src/hooks/useWatchDeep.ts:22:9
    at callWithErrorHandling (http://localhost:5173/node_modules/.vite/deps/chunk-S4KY57GZ.js?v=f3bcf855:1584:18)
    at callWithAsyncErrorHandling (http://localhost:5173/node_modules/.vite/deps/chunk-S4KY57GZ.js?v=f3bcf855:1592:17)
    at job (http://localhost:5173/node_modules/.vite/deps/chunk-S4KY57GZ.js?v=f3bcf855:3181:9)
    at doWatch (http://localhost:5173/node_modules/.vite/deps/chunk-S4KY57GZ.js?v=f3bcf855:3212:7)
    at watch (http://localhost:5173/node_modules/.vite/deps/chunk-S4KY57GZ.js?v=f3bcf855:3069:10)
    at useWatchDeep (http://localhost:5173/src/hooks/useWatchDeep.ts:16:10)
    at setup (http://localhost:5173/src/components/node_selector/TfSelectGpu.vue:23:5)
- Constructor: ReferenceError
```

**Comment by khaledyoussef24** [comment]
verified on devnet


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/62a7ed00-46c4-43a3-afbf-f13a55557e21)

will wait till mainnet release

**Comment by khaledyoussef24** [comment]
verified on mainnet
version :2.5.2


https://github.com/user-attachments/assets/6390b751-9b13-41f8-aac1-17af8dc3c7dc
![Image](https://github.com/user-attachments/assets/fac562e2-0a77-4897-b79f-526d5dada51c)

[test case](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4318587)
