### ISSUE TITLE
Account creation is not working

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#323]
### Description

Account creation is not working and it keeps loading infinitly and the following error appears in the console.

![image](https://github.com/threefoldtech/playground/assets/101194226/d50dc00d-d874-4f04-9ea0-bfcc44470869)

```
ferenceError: require is not defined
    at new BackendStorage (index-db529f9f.js:79:641071)
    at new Algorand (index-db529f9f.js:177:57944)
    at GridClient._connect (index-db529f9f.js:79:645860)
    at createAccount (index-db529f9f.js:211:16657)
    at S (index-db529f9f.js:220:3264)
    at index-db529f9f.js:6:101263
    at callWithErrorHandling (index-db529f9f.js:6:43666)
    at callWithAsyncErrorHandling (index-db529f9f.js:6:43788)
    at callWithAsyncErrorHandling (index-db529f9f.js:6:43925)
    at HTMLButtonElement.r (index-db529f9f.js:6:100958)
```

[Untitled_ May 14, 2023 2_49 PM.webm](https://github.com/threefoldtech/playground/assets/101194226/e7c3f52b-fbb6-4923-8d6d-b0951fcd22c3)

**Comment by mohamedamer453** [comment]
Verified on devnet.

Account Creation is working now.

[Screencast from 11-06-23 18:21:37.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/12084dd8-853f-4c65-9843-451c23ab877c)
