### ISSUE TITLE
🐞 [Bug]: Stellar script failed while getting account

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

https://app.testlodge.com/a/26076/projects/40893/runs/757631/run?selected=33242472&user_id=170529

### Steps To Reproduce

- Go to grid client 
- Edit your script config file 
- Run `yarn run ts-node --project tsconfig-node.json scripts/stellar.ts`

Here're my inputs:
```
  const createAccount: StellarWalletCreateModel = {
    name: "stestt3",
  };

  const account: StellarWalletInitModel = {
    name: "stest4",
    secret: "SCIWNZC65SXTLBY53KAGIPMVYKHHBTD3KPB5OV3OKIUCL2L7LVSRZO5Z",
  };

  const getAccount: BlockchainGetModel = {
    name: "stest4",
  };

  const signMessage: BlockchainSignModel = {
    name: "stest4",
    content: "message",
  };

  const deleteAccount1: BlockchainDeleteModel = {
    name: "stestt3",
  };

  const deleteAccount2: BlockchainDeleteModel = {
    name: "stest4",
  };
```

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
'================= Creating account ================='
{
  name: 'stestt3',
  public_key: 'GBNUONKEGGOMKHBOLA63DW6UFWTVFANRAJWEHWIE62JWX57IS3BBTRIL',
  secret: 'SCLRV7NJYZMFDRUPU5TMRHUTGLFQL66HSX66LUWFTB5VVZ6GWQXOH73B',
  blockchain_type: 'stellar'
}
'================= Creating account ================='
'================= Initializing account ================='
'GAY375MYAVO22BRWDTO72VFWTDJ4M4GCMKXDMLBHHNKZ5VWAISYLNM66'
'================= Initializing account ================='
'================= Listing account ================='
[
  {
    name: 'zeeTest',
    public_key: 'GAY375MYAVO22BRWDTO72VFWTDJ4M4GCMKXDMLBHHNKZ5VWAISYLNM66',
    blockchain_type: 'stellar'
  },
  {
    name: 'zeeTest1',
    public_key: 'GBY65D2YYA6ZXNBBVKDBPEHWGQEZQQKVSBWCMZGPD547SMX7D7VCKRT5',
    blockchain_type: 'stellar'
  },
  {
    name: 'zeeTest5',
    public_key: 'GBDSVD2BGZIRYRTR7X7QNGH6GJVG6RY7UIVQ637GTVYU4RWUWBUXY7EK',
    blockchain_type: 'stellar'
  },
  {
    name: 'stest',
    public_key: 'GAJSIJJQ3RFMJ72VGO4IUCORTWTMBA3FGCMUHMWYXEA2JUVI7FJLWVV3',
    blockchain_type: 'stellar'
  },
  {
    name: 'stest2',
    public_key: 'GAY375MYAVO22BRWDTO72VFWTDJ4M4GCMKXDMLBHHNKZ5VWAISYLNM66',
    blockchain_type: 'stellar'
  },
  {
    name: 'stest3',
    public_key: 'GB7UH4JSXLW2GVRVJ2QIOV43757G7YLOCUVCPHK42Y4AV4HTWMVBDARA',
    blockchain_type: 'stellar'
  },
  {
    name: 'stestt3',
    public_key: 'GBNUONKEGGOMKHBOLA63DW6UFWTVFANRAJWEHWIE62JWX57IS3BBTRIL',
    blockchain_type: 'stellar'
  },
  {
    name: 'stest4',
    public_key: 'GAY375MYAVO22BRWDTO72VFWTDJ4M4GCMKXDMLBHHNKZ5VWAISYLNM66',
    blockchain_type: 'stellar'
  }
]
'================= Listing account ================='
'================= Checking account ================='
true
'================= Checking account ================='
'================= Getting account ================='
{
  name: 'stest4',
  public_key: 'GAY375MYAVO22BRWDTO72VFWTDJ4M4GCMKXDMLBHHNKZ5VWAISYLNM66',
  secret: 'SCIWNZC65SXTLBY53KAGIPMVYKHHBTD3KPB5OV3OKIUCL2L7LVSRZO5Z',
  blockchain_type: 'stellar'
}
'================= Getting account ================='
Validation failed. errors: [
  ValidationError {
    target: StellarWalletBalanceByAddressModel { address: [Object] },
    value: {
      address: 'GAY375MYAVO22BRWDTO72VFWTDJ4M4GCMKXDMLBHHNKZ5VWAISYLNM66'
    },
    property: 'address',
    children: [],
    constraints: { isString: 'address must be a string' }
  }
]
/home/zainab/repos/tfgrid-sdk-ts/packages/grid_client/src/helpers/validator.ts:11
    throw new ValidationError(`Validation failed. errors: ${errors}.`);
          ^
ValidationError: ValidationError: Validation failed. errors: An instance of StellarWalletBalanceByAddressModel has failed the validation:
 - property address has failed the following constraints: isString 
.
    at validateObject (/home/zainab/repos/tfgrid-sdk-ts/packages/grid_client/src/helpers/validator.ts:11:11)
    at Stellar.descriptor.value (/home/zainab/repos/tfgrid-sdk-ts/packages/grid_client/src/helpers/validator.ts:21:7)
    at balanceByAddress (/home/zainab/repos/tfgrid-sdk-ts/packages/grid_client/scripts/stellar.ts:51:36)
    at main (/home/zainab/repos/tfgrid-sdk-ts/packages/grid_client/scripts/stellar.ts:133:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  module: 'Generic'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ramezsaeed** [comment]
More info for the valid and invalid inputs here.

**Comment by samaradel** [comment]
Fixed
