### ISSUE TITLE
🐞 [Bug]: Removing gpu card gives an error

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Removing GPU card gives an error

### Steps To Reproduce

- Go to https://staging.dashboard.dev.grid.tf/#/deploy/node-finder/
- Filter by gpu and open node details
- Remove the GPU card

### which network/s did you face the problem on?

Dev

### version

8529bf1

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/9bdcafd2-1582-474e-9185-127e97fcd42f)

### Relevant log output

```console
[Uncaught Error]
- Message: Cannot read properties of undefined (reading 'vendor')
- Stack: TypeError: Cannot read properties of undefined (reading 'vendor')
   at b (https://staging.dashboard.dev.grid.tf/assets/nodes-bd929ea2.js:1:4719)
   at https://staging.dashboard.dev.grid.tf/assets/nodes-bd929ea2.js:1:3831
   at callWithErrorHandling (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:37:23033)
   at callWithAsyncErrorHandling (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:37:23155)
   at be (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:37:30948)
   at callWithErrorHandling (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:37:23041)
   at flushJobs (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:37:25661)
- Constructor: TypeError

[Uncaught Error]
- Message: Cannot read properties of undefined (reading 'contract')
- Stack: TypeError: Cannot read properties of undefined (reading 'contract')
   at https://staging.dashboard.dev.grid.tf/assets/nodes-bd929ea2.js:1:5789
   at Object.g [as default] (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:37:27498)
   at Proxy.<anonymous> (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:41:294894)
   at renderComponentRoot (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:37:27942)
   at ReactiveEffect.lt [as fn] (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:37:61088)
   at ReactiveEffect.run (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:37:10964)
   at ot.update (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:37:62173)
   at callWithErrorHandling (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:37:23041)
   at flushJobs (https://staging.dashboard.dev.grid.tf/assets/index-15ab5634.js:37:25661)
- Constructor: TypeError
```

**Comment by zaelgohary** [comment]
Work completed:

Removed clearable from v-select.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : b760b10
![Image](https://github.com/user-attachments/assets/e308cd06-6d31-4ec4-9462-e7a742127e2b)
![Image](https://github.com/user-attachments/assets/c405af56-74ef-48e1-aff2-ce78523673fe)

GPU field in gpu nodes can not be cleared now
