### ISSUE TITLE
🐞 [Bug]: set additional fees error TC2443

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

error when setting additional fees on node. found when doing this test https://app.testlodge.com/a/26076/projects/40893/runs/757593/run?run_suite_id=1250928&selected=33260633

### Steps To Reproduce

1. go to your nodes table
2. set additional fees, click save
3. watch error below appear in console

### which network/s did you face the problem on?

Dev

### version

current

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/5f0c27ef-423f-4bda-a598-f521a0947f3c)

### Relevant log output

```console
index-fb0b8f0b.js:16 [Uncaught Error]
- Message: Cannot read properties of undefined (reading 'useIndexAsValue')
- Stack: TypeError: Cannot read properties of undefined (reading 'useIndexAsValue')
    at https://dashboard.dev.grid.tf/assets/index-fb0b8f0b.js:10:35057
    at https://dashboard.dev.grid.tf/assets/index-fb0b8f0b.js:6:58942
    at callWithErrorHandling (https://dashboard.dev.grid.tf/assets/index-fb0b8f0b.js:6:44045)
    at callWithAsyncErrorHandling (https://dashboard.dev.grid.tf/assets/index-fb0b8f0b.js:6:44167)
    at c.__weh.c.__weh (https://dashboard.dev.grid.tf/assets/index-fb0b8f0b.js:6:58721)
    at flushPostFlushCbs (https://dashboard.dev.grid.tf/assets/index-fb0b8f0b.js:6:46281)
    at flushJobs (https://dashboard.dev.grid.tf/assets/index-fb0b8f0b.js:6:46743)
- Constructor: TypeError
```

**Comment by samaradel** [comment]
not reproduced

https://github.com/user-attachments/assets/01beb1ca-df8f-4146-97b1-49a67194cd1f

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- e655b13

<img width="1781" height="1008" alt="Image" src="https://github.com/user-attachments/assets/3d1c0979-8f4a-41d6-a3b2-f1be665bd74e" />
