### ISSUE TITLE
🐞 [Bug]: Search by node id 88 error

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

searching by node id in node finder produces error 

### Steps To Reproduce

1. go to node finder
2. search by node id 88
3. look at error below in console

### which network/s did you face the problem on?

Dev

### version

current

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/750e75be-bfbd-45c2-983d-7cabef8714ff)

### Relevant log output

```console
Error getting node object for node ID 88:  TypeError: Cannot read properties of undefined (reading 'last_deployment_timestamp')
    at fe (index-fb0b8f0b.js:378:74519)
    at async index-fb0b8f0b.js:378:72185
index-fb0b8f0b.js:16 Error getting node object for node ID 131:  AbortError: signal is aborted without reason
    at index-fb0b8f0b.js:43:2621
```

**Comment by scottyeager** [comment]
I'm seeing the second error appearing for a number of mainnet nodes:

```
Error getting node object for node ID 6869:  AbortError: signal is aborted without reason
    at index-fb0b8f0b.js:43:2621
```
```
Error getting node object for node ID 1256:  AbortError: signal is aborted without reason
    at index-fb0b8f0b.js:43:2621
```

This is when searching and opening node details in node finder. This error message also appears:

![image](https://github.com/user-attachments/assets/b90b9715-0529-4f2e-adc2-4606201c0358)

But the nodes are actually online.

**Comment by mahendravarmayadala93** [comment]
I noticed this issue again for the Node : 3758 and it is up on the Gridproxy : https://gridproxy.grid.tf/nodes/3758/status

<img width="643" alt="image" src="https://github.com/user-attachments/assets/642fc4ae-ae20-4d4d-aa5c-b58af27a0d21">

**Comment by mahendravarmayadala93** [comment]
I observed this error on Node 6489, which last reported uptime on October 30, 2024, at 06:40:06 GMT+0000. The client is unable to reach this server as well. 

<img width="675" alt="image" src="https://github.com/user-attachments/assets/60f0286f-39fd-4c77-98ce-d52bb81d7987">

**Comment by amiraabouhadid** [comment]
no err is currently shown for node 88 on devnet

**Comment by amiraabouhadid** [comment]
node 3758 is up as well, no console err is shown when searched by ID in node finder 

<img width="900" alt="Image" src="https://github.com/user-attachments/assets/8079b657-461b-4730-abc9-4bb3ef447e50" />
however when node details are loaded, the following err appears 

<img width="1483" alt="Image" src="https://github.com/user-attachments/assets/5b8cfc26-b4f7-4ca2-9663-6e6ada13df0e" />


```iperf_details_card.vue:74 Empty array returned from the IPerf test

iperf_details_card.vue:44 Error: Can't get the test results, please try again later.
    at getNodeIPerfCard (iperf_details_card.vue:75:15)
    at async iperf_details_card.vue:42:11
content.js:1 Disconnected from polkadot{.js}-0x6e10e163a1550e8d-content
﻿
```

**Comment by amiraabouhadid** [comment]
node 6489 is up and no console err is shown when searched for by ID and when node details are opened 

<img width="1094" alt="Image" src="https://github.com/user-attachments/assets/87f4e7b1-5891-4ee4-b07e-ac05ccf4cf0e" />
