### ISSUE TITLE
🐞 [Bug]: Cannot use `grid_client` pkg outside the ts-sdk

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#3584]
### which package/s did you face the problem with?

grid_client

### What happened?

when I installed the latest version of ```grid_client``` pkg ```2.6.0-rc2``` outside the ts-sdk and used the ```scripts/checkNodeAlive.ts``` script I got ```Error: Cannot find module '@threefold/monitoring'```

### Steps To Reproduce

- create pkg outside ts-sdk
- install the latest version of grid client ```2.6.0-rc2```
- run any script

### version

```2.6.0-rc2```

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/55348335-bd26-42e1-8706-9759b4972b17)

### Relevant log output

```console
Error: Cannot find module '@threefold/monitoring'
Require stack:
- /media/samar/DATA/github/threefoldtech/grid_client_pkg/node_modules/@threefold/grid_client/dist/node/manageURLs.js
- /media/samar/DATA/github/threefoldtech/grid_client_pkg/node_modules/@threefold/grid_client/dist/node/client.js
- /media/samar/DATA/github/threefoldtech/grid_client_pkg/node_modules/@threefold/grid_client/dist/node/index.js
- /media/samar/DATA/github/threefoldtech/grid_client_pkg/scripts/checkNodeAlive.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/media/samar/DATA/github/threefoldtech/grid_client_pkg/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/media/samar/DATA/github/threefoldtech/grid_client_pkg/node_modules/@threefold/grid_client/dist/node/manageURLs.js:4:22)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (/media/samar/DATA/github/threefoldtech/grid_client_pkg/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/media/samar/DATA/github/threefoldtech/grid_client_pkg/node_modules/@threefold/grid_client/dist/node/manageURLs.js',
    '/media/samar/DATA/github/threefoldtech/grid_client_pkg/node_modules/@threefold/grid_client/dist/node/client.js',
    '/media/samar/DATA/github/threefoldtech/grid_client_pkg/node_modules/@threefold/grid_client/dist/node/index.js',
    '/media/samar/DATA/github/threefoldtech/grid_client_pkg/scripts/checkNodeAlive.ts'
  ]
}
error Command failed with exit code 1.
```

**Comment by A-Harby** [comment]
Verified, Devnet `@threefold/grid_client": "^2.6.0-rc3`.

I tested the same scenario and a couple other scripts of the main functionality, like VM, and they all worked fine.
![image](https://github.com/user-attachments/assets/4394868f-9aa2-486e-8bb8-a26942370c9b)
![image](https://github.com/user-attachments/assets/178dfceb-7f53-45fd-abf0-07fc88d50189)

**Comment by A-Harby** [comment]
Add section with new created test cases: [Grid Client NPM Package Contains 5 test cases](https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=455924#suite_section_455924)

![image](https://github.com/user-attachments/assets/21c53bce-2c8a-4a48-b9b3-5293f6a3e6cd)
