### ISSUE TITLE
🐞 [Bug]: Zmount tests are failing

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

 FAIL  tests/modules/zmount.test.ts
  Zmount module
    ✓ Zmount instance is of type Zmount. (2 ms)
    ✕ Min value for size. (2 ms)
    ✕ Max value for size. (1 ms)
    ✕ Size doesn't accept decimal value.
    ✓ Size empty value.
    ✕ Size negative value. (1 ms)

### which network/s did you face the problem on?

Dev

### version

2.6.1

### Relevant screenshots/screen records

<img width="720" alt="Screenshot 2024-12-08 at 5 57 37 PM" src="https://github.com/user-attachments/assets/eb29944c-d37a-4d4c-a0b6-b0bc06d4529e">

### Relevant log output

```console
khaledyoussef@Khaleds-MacBook-Air grid_client % yarn workspace @threefold/grid_client test tests/modules/zmount.test.ts  
yarn workspace v1.19.0
yarn run v1.19.0
$ jest tests/modules/zmount.test.ts
 FAIL  tests/modules/zmount.test.ts
  Zmount module
    ✓ Zmount instance is of type Zmount. (2 ms)
    ✕ Min value for size. (2 ms)
    ✕ Max value for size. (1 ms)
    ✕ Size doesn't accept decimal value.
    ✓ Size empty value.
    ✕ Size negative value. (1 ms)

  ● Zmount module › Min value for size.

    expect(received).toThrow()

    Received function did not throw

      18 |     const result = () => zmount.challenge();
      19 |
    > 20 |     expect(result).toThrow();
         |                    ^
      21 |   });
      22 |
      23 |   test("Max value for size.", () => {

      at Object.<anonymous> (tests/modules/zmount.test.ts:20:20)

  ● Zmount module › Max value for size.

    thrown: ValidationError {
      "children": Array [],
      "constraints": Object {
        "max": "size must not be greater than 10995116277760",
      },
      "property": "size",
      "target": Object {
        "size": 110381289062500,
      },
      "value": 110381289062500,
    }

      21 |   });
      22 |
    > 23 |   test("Max value for size.", () => {
         |   ^
      24 |     const size = 100 * 1025 ** 4;
      25 |
      26 |     zmount.size = size;

      at tests/modules/zmount.test.ts:23:3
      at Object.<anonymous> (tests/modules/zmount.test.ts:8:1)

  ● Zmount module › Size doesn't accept decimal value.

    thrown: ValidationError {
      "children": Array [],
      "constraints": Object {
        "isInt": "size must be an integer number",
        "min": "size must not be less than 104857600",
      },
      "property": "size",
      "target": Object {
        "size": 1.5,
      },
      "value": 1.5,
    }

      31 |   });
      32 |
    > 33 |   test("Size doesn't accept decimal value.", () => {
         |   ^
      34 |     const size = 1.5;
      35 |
      36 |     zmount.size = size;

      at tests/modules/zmount.test.ts:33:3
      at Object.<anonymous> (tests/modules/zmount.test.ts:8:1)

  ● Zmount module › Size negative value.

    thrown: ValidationError {
      "children": Array [],
      "constraints": Object {
        "min": "size must not be less than 104857600",
      },
      "property": "size",
      "target": Object {
        "size": -1,
      },
      "value": -1,
    }

      47 |   });
      48 |
    > 49 |   test("Size negative value.", () => {
         |   ^
      50 |     const negative_size = -1;
      51 |
      52 |     zmount.size = negative_size;

      at tests/modules/zmount.test.ts:49:3
      at Object.<anonymous> (tests/modules/zmount.test.ts:8:1)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 2 passed, 6 total
Snapshots:   0 total
Time:        4.625 s
Ran all test suites matching /tests\/modules\/zmount.test.ts/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/khaledyoussef/.nvm/versions/node/v18.20.5/bin/node
Arguments: /Users/khaledyoussef/work/new/tfgrid-sdk-ts/.yarn/releases/yarn-1.19.0.cjs test tests/modules/zmount.test.ts
Directory: /Users/khaledyoussef/work/new/tfgrid-sdk-ts/packages/grid_client
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
khaledyoussef@Khaleds-MacBook-Air grid_client %
```

**Comment by ramezsaeed** [comment]
Duplicate to: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3523
