### ISSUE TITLE
TFChain integration tests randomly fail with different errors

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#375]
### Description

The integrations tests for tfchain have been randomly failing for a while now and after some investigation these are the issues that i found.

I ran each test multiple times while debugging this issue but i wasn't able to detect a pattern or cause for these errors.

The only test that didn't produce any of these errors is `TC1261 - TFChain: Create Account` other than that the following errors appear randomly in the rest of the tests 

- I think this one is not an issue but it's reported as an error but it mentions that it's `Normal connection closure` from the chain and it doesn't cause the tests to fail.

```bash
  console.error
    2023-05-28 10:56:00          API-WS: Error: disconnected from wss://tfchain.dev.grid.tf/ws: 1000:: Normal connection closure
        at W3CWebSocket.value (/home/mohamed/Desktop/Threefold Repos/sdkts_temp/tfgrid-sdk-ts/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:221:23)
        at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/mohamed/Desktop/Threefold Repos/sdkts_temp/tfgrid-sdk-ts/node_modules/yaeti/lib/EventTarget.js:107:17)
        at W3CWebSocket.onClose (/home/mohamed/Desktop/Threefold Repos/sdkts_temp/tfgrid-sdk-ts/node_modules/websocket/lib/W3CWebSocket.js:228:10)
        at WebSocketConnection.<anonymous> (/home/mohamed/Desktop/Threefold Repos/sdkts_temp/tfgrid-sdk-ts/node_modules/websocket/lib/W3CWebSocket.js:201:17)
        at WebSocketConnection.emit (node:events:513:28)
        at WebSocketConnection.Object.<anonymous>.WebSocketConnection.handleSocketClose (/home/mohamed/Desktop/Threefold Repos/sdkts_temp/tfgrid-sdk-ts/node_modules/websocket/lib/WebSocketConnection.js:389:14)
        at TLSSocket.emit (node:events:525:35)
        at node:net:322:12
        at TCP.done (node:_tls_wrap:588:7)

      at apply (../../node_modules/@polkadot/util/cjs/logger.js:62:22)
      at Object.error (../../node_modules/@polkadot/util/cjs/logger.js:118:14)
      at ../../node_modules/@polkadot/rpc-provider/cjs/ws/index.js:390:15
          at async Promise.all (index 0)
```

- One of the errors that randomly appear, this is the most common one and it's the one that caused most of the recent failure for nightly runs

```bash
TypeError: Cannot read properties of undefined (reading 'connect')

      at EventEmitter.connect (../../node_modules/@polkadot/api/cjs/base/index.js:45:26)
      at EventEmitter.emit (../../node_modules/eventemitter3/index.js:180:35)
      at ApiPromise.emit (../../node_modules/@polkadot/api/cjs/base/Events.js:22:31)
      at ApiPromise._onProviderDisconnect2 (../../node_modules/@polkadot/api/cjs/base/Init.js:449:8)
      at EventEmitter.<anonymous> (../../node_modules/@polkadot/api/cjs/base/Init.js:103:148)
      at EventEmitter.emit (../../node_modules/eventemitter3/index.js:180:35)
      at WsProvider.value (../../node_modules/@polkadot/rpc-provider/cjs/ws/index.js:215:88)
      at W3CWebSocket.value (../../node_modules/@polkadot/rpc-provider/cjs/ws/index.js:242:70)
      at W3CWebSocket._dispatchEvent [as dispatchEvent] (../../node_modules/yaeti/lib/EventTarget.js:107:17)
      at W3CWebSocket.onClose (../../node_modules/websocket/lib/W3CWebSocket.js:228:10)
      at WebSocketConnection.<anonymous> (../../node_modules/websocket/lib/W3CWebSocket.js:201:17)
      at WebSocketConnection.Object.<anonymous>.WebSocketConnection.handleSocketClose (../../node_modules/websocket/lib/WebSocketConnection.js:389:14)
```

and the test is not finished and it just hangs so it probably will not stop till it times out.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/3c55a198-0801-4f9b-87aa-cd40e992f3f3)

- Sometimes it gets stuck at this step and then it waits for 5 mins (default jest timeout)

```bash
  console.error
    2023-05-28 14:11:11        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

      at apply (../../node_modules/@polkadot/util/cjs/logger.js:62:22)
      at Object.error (../../node_modules/@polkadot/util/cjs/logger.js:118:14)
      at logErrorMessage (../../node_modules/@polkadot/rpc-core/cjs/bundle.js:79:5)
      at errorHandler (../../node_modules/@polkadot/rpc-core/cjs/bundle.js:335:11)
      at ../../node_modules/@polkadot/rpc-core/cjs/bundle.js:309:9

  console.error
    2023-05-28 14:11:11             DRR: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

      at apply (../../node_modules/@polkadot/util/cjs/logger.js:62:22)
      at Object.error (../../node_modules/@polkadot/util/cjs/logger.js:118:14)
      at ERR (../../node_modules/@polkadot/rpc-core/cjs/util/drr.js:25:5)
      at ../../node_modules/rxjs/src/internal/operators/catchError.ts:117:35
      at OperatorSubscriber._this._error (../../node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:79:13)
      at OperatorSubscriber.Object.<anonymous>.Subscriber.error (../../node_modules/rxjs/src/internal/Subscriber.ts:91:12)
      at errorHandler (../../node_modules/@polkadot/rpc-core/cjs/bundle.js:336:20)
      at ../../node_modules/@polkadot/rpc-core/cjs/bundle.js:309:9

  console.error
    2023-05-28 14:11:11        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

      at apply (../../node_modules/@polkadot/util/cjs/logger.js:62:22)
      at Object.error (../../node_modules/@polkadot/util/cjs/logger.js:118:14)
      at logErrorMessage (../../node_modules/@polkadot/rpc-core/cjs/bundle.js:79:5)
      at ../../node_modules/@polkadot/rpc-core/cjs/bundle.js:381:194
```

and then it fails because it exceeded the timeout.

```
    thrown: "Exceeded timeout of 300000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
```

**Comment by mohamedamer453** [comment]
Verified on devnet.

The mentioned errors are not reproducible any more and the tests are working fine. https://github.com/threefoldtech/tfgrid-sdk-ts/runs/13838393897#r0s8
