### ISSUE TITLE
Deleting a contract that is in `GracPeriod` is not handled correctly

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#463]
### Description

Deleting a contract that is in `GracPeriod` is not handled correctly.

An error appears in the console mentioning that the fees to delete the contract is not enough but in the ui there's no error and it just keeps loading forever.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4692b3bb-2efe-4b26-b1dd-06d10e1b935f)

### Expected Behavior

The contract shouldn't be deleted, and a clear error should be displayed to the user.

### Steps to reproduce

- Navigate to the contracts list.
- Delete any contract in `GracePeriod`

**Comment by 0oM4R** [comment]
this error is happening while deleting the keys the client stucks on that error which leads to the btn to be loading forever,
tried to investigate and I think the issue occurred on 
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/8c14e7b5fb03bf86ecb61330657b1176b62fe28d/packages/tfchain_client/src/client.ts#L317
the callback is never called, and there is some logs 
````txt
yarn run v1.22.19
$ /home/kassem/tfgrid-sdk-ts/node_modules/.bin/ts-node --project tsconfig-node.json scripts/name.ts
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 10.4.2	node_modules/@polkadot/util/cjs
	cjs 9.7.2 	node_modules/@polkadot/rpc-provider/node_modules/@polkadot/util/cjs
Credentials not all found in env variables. Loading all credentials from default config.json...
2023-06-05 16:31:06        API/INIT: RPC methods not decorated: transaction_unstabale_submitAndWatch, transaction_unstable_unwatch
2023-06-05 16:31:06        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
Validation succeed
Lock acquired
2023-06-05 16:31:08        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
2023-06-05 16:31:08             DRR: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
2023-06-05 16:31:08        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
/home/kassem/tfgrid-sdk-ts/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:34
    throw new _error.default(`${code}: ${message}${formatErrorData(data)}`, code, data);
          ^
RpcError: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
    at checkError (/home/kassem/tfgrid-sdk-ts/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:34:11)
    at RpcCoder.decodeResponse (/home/kassem/tfgrid-sdk-ts/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:54:5)
    at WsProvider.value (/home/kassem/tfgrid-sdk-ts/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:297:90)
    at W3CWebSocket.value [as onmessage] (/home/kassem/tfgrid-sdk-ts/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:277:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/kassem/tfgrid-sdk-ts/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/kassem/tfgrid-sdk-ts/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/kassem/tfgrid-sdk-ts/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (node:events:513:28)
    at WebSocketConnection.emit (node:domain:489:12)
    at WebSocketConnection.processFrame (/home/kassem/tfgrid-sdk-ts/node_modules/websocket/lib/WebSocketConnection.js:554:26)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

````

**Comment by mohamedamer453** [comment]
i tried to delete a contract in grace period and it doesn't get stuck anymore. and it looked like it was deleted but when i navigated to the deployments page then to the contracts page it appeared again. but after reloading the page it disappeared from the list.


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/c97a2a5a-454d-4232-aee1-ebcb8cccd9c1


also another question related to this. is it allowed to delete contracts while they're in grace period?

**Comment by 0oM4R** [comment]
@mohamedamer453  This is normal; deleting contracts may take a while, we add a warning before deleting to inform the user about that
yes it is allowed because if the  user can't delete it the cost will keep increasing
