### ISSUE TITLE
Decoding calculator: Invalid base58 character "l"

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#562]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/69c969c1-f851-42cf-8ca3-5c37bb9b5dc5)

```
{"refTime":272785000,"proofSize":0},"class":"Normal","paysFee":"Yes"}]
logger.js:54 2023-06-13 11:58:04             VEC: Unable to decode on index 0 createType(Lookup0):: Decoding calculator: Invalid base58 character "l" (0x6c) at index 2
b @ logger.js:54
logger.js:54 2023-06-13 11:58:04        RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: createType(Vec<StorageKey>):: createType(Lookup0):: Decoding calculator: Invalid base58 character "l" (0x6c) at index 2
b @ logger.js:54
type.js:57 Uncaught (in promise) Error: createType(Vec<StorageKey>):: createType(Lookup0):: Decoding calculator: Invalid base58 character "l" (0x6c) at index 2
    at Gi (type.js:57:18)
    at Rf.createTypeUnsafe (registry.js:318:12)
    at bundle.js:346:50
    at Array.map (<anonymous>)
    at yk._formatInputs (bundle.js:346:19)
    at a (bundle.js:213:27)
    at e._subscribe (bundle.js:223:9)
    at e._trySubscribe (Observable.js:38:25)
    at Observable.js:32:31
    at Q (errorContext.js:19:9)
logger.js:54 2023-06-13 11:58:05             VEC: Unable to decode on index 0 createType(Lookup0):: Decoding calculator: Invalid base58 character "l" (0x6c) at index 2
b @ logger.js:54
logger.js:54 2023-06-13 11:58:05        RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: createType(Vec<StorageKey>):: createType(Lookup0):: Decoding calculator: Invalid base58 character "l" (0x6c) at index 2
b @ logger.js:54
type.js:57 Uncaught (in promise) Error: createType(Vec<StorageKey>):: createType(Lookup0):: Decoding calculator: Invalid base58 character "l" (0x6c) at index 2
    at Gi (type.js:57:18)
    at Rf.createTypeUnsafe (registry.js:318:12)
    at bundle.js:346:50
    at Array.map (<anonymous>)
    at yk._formatInputs (bundle.js:346:19)
    at a (bundle.js:213:27)
    at e._subscribe (bundle.js:223:9)
    at e._trySubscribe (Observable.js:38:25)
    at Observable.js:32:31
    at Q (errorContext.js:19:9)
logger.js:54 2023-06-13 11:58:06             VEC: Unable to decode on index 0 createType(Lookup0):: Decoding calculator: Invalid base58 character "l" (0x6c) at index 2
b @ logger.js:54
logger.js:54 2023-06-13 11:58:06        RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: createType(Vec<StorageKey>):: createType(Lookup0):: Decoding calculator: Invalid base58 character "l" (0x6c) at index 2
b @ logger.js:54
type.js:57 Uncaught (in promise) Error: createType(Vec<StorageKey>):: createType(Lookup0):: Decoding calculator: Invalid base58 character "l" (0x6c) at index 2
    at Gi (type.js:57:18)
    at Rf.createTypeUnsafe (registry.js:318:12)
    at bundle.js:346:50
    at Array.map (<anonymous>)
    at yk._formatInputs (bundle.js:346:19)
    at a (bundle.js:213:27)
    at e._subscribe (bundle.js:223:9)
    at e._trySubscribe (Observable.js:38:25)
    at Observable.js:32:31
    at Q (errorContext.js:19:9)

```

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/594

**Comment by A-Harby** [comment]
Verified, on QA 2.0.0-rc14.
Error is fixed and doesn't display in the console anymore.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8e4eca66-f95c-4766-9fb7-7513490bfc57)
