### ISSUE TITLE
how to run the dev server for playground?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#610]
I cloned the repo, did `yarn install`, and then `yarn workspace @threefold/playground dev`

```
✘ [ERROR] Failed to resolve entry for package "@threefold/grid_client". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    ../../node_modules/esbuild/lib/main.js:1360:21:
      1360 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///home/xmonader/wspace/tfgrid-sdk-ts/packages/playground/node_modules/vite/dist/node/chunks/dep-1f986b87.js:23382:11)
    at resolvePackageEntry (file:///home/xmonader/wspace/tfgrid-sdk-ts/packages/playground/node_modules/vite/dist/node/chunks/dep-1f986b87.js:23379:5)
    at tryNodeResolve (file:///home/xmonader/wspace/tfgrid-sdk-ts/packages/playground/node_modules/vite/dist/node/chunks/dep-1f986b87.js:23113:20)
    at Context.resolveId (file:///home/xmonader/wspace/tfgrid-sdk-ts/packages/playground/node_modules/vite/dist/node/chunks/dep-1f986b87.js:22874:28)
    at Object.resolveId (file:///home/xmonader/wspace/tfgrid-sdk-ts/packages/playground/node_modules/vite/dist/node/chunks/dep-1f986b87.js:42847:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///home/xmonader/wspace/tfgrid-sdk-ts/packages/playground/node_modules/vite/dist/node/chunks/dep-1f986b87.js:43145:26)
    at async file:///home/xmonader/wspace/tfgrid-sdk-ts/packages/playground/node_modules/vite/dist/node/chunks/dep-1f986b87.js:43322:34
    at async requestCallbacks.on-resolve (/home/xmonader/wspace/tfgrid-sdk-ts/node_modules/esbuild/lib/main.js:1360:22)
    at async handleRequest (/home/xmonader/wspace/tfgrid-sdk-ts/node_modules/esbuild/lib/main.js:723:13)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/esbuild/lib/main.js:1279:20:
      1279 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/xmonader/wspace/tfgrid-sdk-ts/packages/playground/node_modules/vite/dist/node/chunks/dep-1f986b87.js:43312:19)
    at handlePlugins (/home/xmonader/wspace/tfgrid-sdk-ts/node_modules/esbuild/lib/main.js:1279:21)

  The plugin "vite:dep-scan" was triggered by this import

    src/utils/deploy_helpers.ts:1:45:
      1 │ import { generateString, NetworkModel } from "@threefold/grid_client";
        ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~~


    at failureErrorWithLog (/home/xmonader/wspace/tfgrid-sdk-ts/node_modules/esbuild/lib/main.js:1636:15)
    at /home/xmonader/wspace/tfgrid-sdk-ts/node_modules/esbuild/lib/main.js:1048:25
    at runOnEndCallbacks (/home/xmonader/wspace/tfgrid-sdk-ts/node_modules/esbuild/lib/main.js:1471:45)
    at buildResponseToResult (/home/xmonader/wspace/tfgrid-sdk-ts/node_modules/esbuild/lib/main.js:1046:7)
    at /home/xmonader/wspace/tfgrid-sdk-ts/node_modules/esbuild/lib/main.js:1058:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/home/xmonader/wspace/tfgrid-sdk-ts/node_modules/esbuild/lib/main.js:1057:54)
    at handleRequest (/home/xmonader/wspace/tfgrid-sdk-ts/node_modules/esbuild/lib/main.js:723:19)
    at handleIncomingPacket (/home/xmonader/wspace/tfgrid-sdk-ts/node_modules/esbuild/lib/main.js:745:7)
    at Socket.readFromStdout (/home/xmonader/wspace/tfgrid-sdk-ts/node_modules/esbuild/lib/main.js:673:7)

```

```
➜  tfgrid-sdk-ts git:(development) node -v
v18.12.1

```

**Comment by Mahmoud-Emad** [comment]
can you please make build to the whole repo.
