### ISSUE TITLE
An error related to `dao` appears in the console after logging in

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#859]
### Description

An error appears in the console after logging in to any account.

[Untitled_ Jul 26, 2023 4_38 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4af969d9-085a-46ac-913c-a4d2a10544c7)

```
Failed to get proposal: TypeError: Cannot read properties of undefined (reading 'dao')
    at d (dao.ts:43:34)
    at v.getProposal (actions.ts:72:31)
    at Array.<anonymous> (vuex.esm.js:851:23)
    at v.dispatch (vuex.esm.js:516:13)
    at v.dispatch (vuex.esm.js:406:21)
    at a.mounted (VotePopup.vue:15:23)
    at Zt (vue.runtime.esm.js:3017:61)
    at Lr (vue.runtime.esm.js:4031:13)
    at Object.insert (vue.runtime.esm.js:4423:13)
    at T (vue.runtime.esm.js:6942:38)
```

### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf/
- Login with your account.
- Check the console.

### Environment

- Network: `devnet`
- Dashboard Version: `2.1.0-rc3`

**Comment by 0oM4R** [comment]
as mentioned in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/838#issuecomment-1647491401 We need to handle it on the client; this is not related to the dashboard, as I understood.
