### ISSUE TITLE
Socket Error: read ETIMEDOUT disconnected from wss://tfchain.grid.tf/ws

### ISSUE THREAD

**Issue by costarassco** [threefoldtech/tfgrid-sdk-ts#992]
### Description

I have a service allowing users to connect to the Grid using the GridClient.
The code is provided in the "Steps to reproduce" section

The connection with the grid client can be a quite long and sometimes in several hours,
I do get such an error: "API-WS: disconnected from wss://tfchain.grid.tf/ws: 1006:: Socket Error: read ETIMEDOUT"
All the details can be found in the "Logs" section
 
I have put everything what's possible in the try-catch block, but I still can't handle this error, which destroying my node connection

Can you please help me with this? I can't use the grid client with such erros at all :( 

I am using 2.0.0-rc6

EDIT:
I also use this functionality btw https://github.com/threefoldtech/grid_weblets/blob/development/src/utils/findNodes.ts

### Steps to reproduce

```
import { GridClient, NetworkEnv } from "@threefold/grid_client";

const options = {
  network: NetworkEnv.main,
  mnemonic,
  storeSecret: "coolSecretPhrase",
};

const gridClient = new GridClient(options);
await gridClient.connect();
```

### Logs/Alerts

```
API-WS: disconnected from wss://tfchain.grid.tf/ws: 1006:: Socket Error: read ETIMEDOUT

/my_cool_folder/node_modules/@threefold/tfchain_client/node_modules/@polkadot/api/cjs/base/index.js:45
    return this._rpcCore.connect();
                         ^
TypeError: Cannot read properties of undefined (reading 'connect')
    at EventEmitter.connect (/my_cool_folder/node_modules/@threefold/tfchain_client/node_modules/@polkadot/api/cjs/base/index.js:45:26)
    at EventEmitter.emit (/my_cool_folder/node_modules/@threefold/tfchain_client/node_modules/eventemitter3/index.js:180:35)
    at ApiPromise.emit (/my_cool_folder/node_modules/@threefold/tfchain_client/node_modules/@polkadot/api/cjs/base/Events.js:22:31)
    at ApiPromise._onProviderDisconnect2 (/my_cool_folder/node_modules/@threefold/tfchain_client/node_modules/@polkadot/api/cjs/base/Init.js:449:8)
    at EventEmitter.<anonymous> (/my_cool_folder/node_modules/@threefold/tfchain_client/node_modules/@polkadot/api/cjs/base/Init.js:103:148)
    at EventEmitter.emit (/my_cool_folder/node_modules/@threefold/tfchain_client/node_modules/eventemitter3/index.js:180:35)
    at WsProvider.value (/my_cool_folder/node_modules/@threefold/tfchain_client/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:215:88)
    at W3CWebSocket.value (/my_cool_folder/node_modules/@threefold/tfchain_client/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:242:70)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/my_cool_folder/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/my_cool_folder/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/my_cool_folder/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:513:28)
    at WebSocketConnection.handleSocketClose (/my_cool_folder/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at TLSSocket.emit (node:events:525:35)
    at node:net:301:12
    at TCP.done (node:_tls_wrap:588:7)
    
 ```

**Comment by costarassco** [comment]
> Still investigating, created script to connect on the grid client module and updated the client connect method.

as I mentioned it's necessary to keep the connection quite long, afterwards you will notice this issue or you can notice the scenario when the gridClient doesn't have the calculator or balance objects

**Comment by costarassco** [comment]
if I connect several times for a period of time with disconnection just right after an operation's finish I get this error as well:

```
RPC-CORE: queryStorageAt(keys: Vec<StorageKey>, at?: BlockHash): Vec<StorageChangeSet>:: disconnected from wss://tfchain.grid.tf/ws: 1000:: Normal connection closure
Error: disconnected from wss://tfchain.grid.tf/ws: 1000:: Normal connection closure
    at W3CWebSocket.value (/project/node_modules/@threefold/tfchain_client/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:221:23)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/project/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/project/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/project/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:513:28)
    at WebSocketConnection.handleSocketClose (/project/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at TLSSocket.emit (node:events:525:35)
    at node:net:301:12
    at TCP.done (node:_tls_wrap:588:7)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by Mahmoud-Emad** [comment]
Update: added one more fix in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1031/

**Comment by khaledyoussef24** [comment]
the connection script works fine after reconnecting 
> This script creates 2 instances of the grid client, then after 10 minutes, it performs a query on both instances.
> 
> ### Steps:
> * Connect to the grid
> * Close the internet connection
> * After 9 minutes, open the internet connection again
> 
> In the tenth minute the grid should automatically reconnect and request the twin ID.

![Screenshot from 2023-08-24 10-57-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e876ef54-4df8-40ec-af8f-3717ad6d7df8)
verified

**Comment by costarassco** [comment]
@khaledyoussef24 hi, thank you for your time, but I get such an error in this condition:

```
The connection with the grid client can be a quite long and sometimes in several hours,
I do get such an error:
```

do you have a script that lets reconnect to the websocket server if it's disconnected?

**Comment by costarassco** [comment]
I also left this comment last week https://github.com/threefoldtech/tfgrid-sdk-ts/issues/992#issuecomment-1681770841
